# Copyright 2023-2024 Blue Brain Project / EPFL

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Main importer of bluecellulab."""

import importlib_resources as resources
import logging
import os
from pathlib import Path
from types import ModuleType
from typing import Optional

import neuron

from bluecellulab.exceptions import BluecellulabError
from bluecellulab.mod_compilation import ModCompilationError, compile_mechanisms
from bluecellulab.utils import CaptureOutput, run_once


logger = logging.getLogger(__name__)


def import_mod_lib(
    neuron: ModuleType, mechanisms_dirs: Optional[list[Path]] = None
) -> str:
    """Import mod files.

    Resolution order:
    1. ``BLUECELLULAB_MOD_LIBRARY_PATH`` env var, if set (explicit override).
    2. `mechanisms_dirs` (e.g. a SONATA circuit's ``mechanisms_dir``), if not
       ``None``: the mod files found there, plus BlueCelluLab's own bundled
       "technical" mod files (see `bluecellulab.mod_compilation`), are
       compiled (or a cached compilation is reused) and the resulting
       library is loaded. Note this branch is taken whenever a SONATA
       circuit is loaded, even if it declares no `mechanisms_dir` of its own
       (i.e. `mechanisms_dirs == []`), since BlueCelluLab's own mod files
       still need to be compiled and loaded in that case.
    3. An ``x86_64`` folder in the current working directory, for manual
       ``nrnivmodl`` workflows (e.g. single-cell, non-SONATA usage).
    """
    res = ""
    if 'BLUECELLULAB_MOD_LIBRARY_PATH' in os.environ:
        # Check if the current directory contains 'x86_64'.
        if os.path.isdir('x86_64'):
            raise BluecellulabError("BLUECELLULAB_MOD_LIBRARY_PATH is set"
                                    " and current directory contains the x86_64 folder."
                                    " Please remove one of them.")

        mod_lib_path = os.environ["BLUECELLULAB_MOD_LIBRARY_PATH"]
        if mod_lib_path.endswith(".so"):
            neuron.h.nrn_load_dll(mod_lib_path)
        else:
            neuron.load_mechanisms(mod_lib_path)
        res = mod_lib_path
    elif mechanisms_dirs is not None:
        if os.path.isdir('x86_64'):
            raise BluecellulabError(
                "A SONATA circuit is being loaded and the current"
                " directory contains an x86_64 folder. Please remove the"
                " x86_64 folder, or load mechanisms manually via"
                " BLUECELLULAB_MOD_LIBRARY_PATH instead."
            )

        try:
            libnrnmech = compile_mechanisms(mechanisms_dirs)
        except ModCompilationError as e:
            raise BluecellulabError(f"Failed to compile circuit mod files: {e}") from e

        if libnrnmech is None:
            res = "No mechanisms are loaded."
        else:
            neuron.h.nrn_load_dll(str(libnrnmech))
            res = str(libnrnmech)
    elif os.path.isdir('x86_64'):
        # NEURON 8.* automatically load these mechamisms
        res = os.path.abspath('x86_64')
    else:
        res = "No mechanisms are loaded."

    return res


def _register_legacy_morphio_wrapper_alias() -> None:
    """Expose the H5 morphology reader as a top-level ``morphio_wrapper``.

    Emodel hoc templates generated by older BluePyOpt / neurodamus pipelines
    load the reader with a bare import::

        nrnpython("from morphio_wrapper import MorphIOWrapper")

    bluecellulab ships it as ``bluecellulab.cell.morphio_wrapper`` (and its own
    ``MorphIO.hoc`` uses that dotted path), so with such a template the bare
    import fails, the hoc prints
    ".h5 morphlogy used but cannot load 'morphio_wrapper'." and calls
    ``quit()``, which terminates the whole process.

    Registering the alias keeps those templates working without having to edit
    circuit data. ``setdefault`` is used so a real top-level ``morphio_wrapper``
    module (e.g. provided by another package) always takes precedence.
    """
    import sys

    from bluecellulab.cell import morphio_wrapper

    sys.modules.setdefault("morphio_wrapper", morphio_wrapper)


def import_hoc(neuron: ModuleType) -> None:
    """Import hoc dependencies."""
    _register_legacy_morphio_wrapper_alias()
    neuron.h.load_file("stdrun.hoc")  # nrn
    hoc_files = [
        "Cell.hoc",  # ND
        "TDistFunc.hoc",  # ND, test dependency
        "TStim.hoc",  # ND
        "MorphIO.hoc",  # H5 morphology support (loaded after Cell.hoc)
    ]

    for hoc_file in hoc_files:
        hoc_file_path = str(resources.files("bluecellulab") / f"hoc/{hoc_file}")
        with CaptureOutput() as stdoud:
            neuron.h.load_file(hoc_file_path)
            logger.debug(f"Loaded {hoc_file}. stdout from the hoc: {stdoud}")


def print_header(neuron: ModuleType, mod_lib_path: str) -> None:
    """Print bluecellulab header to stdout."""
    logger.debug(f"Imported NEURON from: {neuron.__file__}")
    logger.debug(f"Mod lib: {mod_lib_path}")


@run_once
def _load_mod_files(mechanisms_dirs: Optional[list[Path]] = None) -> None:
    """Import hoc and mod files.

    NEURON only allows mechanisms to be loaded once per process, so this is
    guarded with `run_once`: only the first call (whichever happens first)
    actually loads anything, later calls are no-ops. `mechanisms_dirs` is
    only meaningful on that first call.
    """
    logger.debug("Loading the mod files.")
    mod_lib_paths = import_mod_lib(neuron, mechanisms_dirs)
    _load_mod_files.loaded_with = mechanisms_dirs
    print_header(neuron, mod_lib_paths)


_load_mod_files.loaded_with = None


def load_mod_files_for_circuit(mechanisms_dirs: Optional[list[Path]]) -> None:
    """Load mod files declared by a circuit (e.g. SONATA `mechanisms_dir`).

    If mod files were already loaded earlier in this process with a
    different set of directories, logs a warning: NEURON does not support
    swapping out mechanisms once loaded, so the earlier set stays in effect.
    """
    if (
        _load_mod_files.has_run
        and mechanisms_dirs
        and mechanisms_dirs != _load_mod_files.loaded_with
    ):
        logger.warning(
            "Mod files were already loaded (with %s) earlier in this process;"
            " the requested mechanisms_dirs %s cannot also be loaded."
            " NEURON only supports loading mechanisms once per process.",
            _load_mod_files.loaded_with,
            mechanisms_dirs,
        )
    _load_mod_files(mechanisms_dirs)


def load_mod_files(func):
    def wrapper(*args, **kwargs):
        _load_mod_files()
        return func(*args, **kwargs)
    return wrapper
