# Copyright 2023-2024 Blue Brain Project / EPFL

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Main importer of bluecellulab."""

import importlib_resources as resources
import logging
import os
from types import ModuleType

import neuron

from bluecellulab.exceptions import BluecellulabError
from bluecellulab.utils import CaptureOutput, run_once


logger = logging.getLogger(__name__)


def import_mod_lib(neuron: ModuleType) -> str:
    """Import mod files."""
    res = ""
    if 'BLUECELLULAB_MOD_LIBRARY_PATH' in os.environ:
        # Check if the current directory contains 'x86_64'.
        if os.path.isdir('x86_64'):
            raise BluecellulabError("BLUECELLULAB_MOD_LIBRARY_PATH is set"
                                    " and current directory contains the x86_64 folder."
                                    " Please remove one of them.")

        mod_lib_path = os.environ["BLUECELLULAB_MOD_LIBRARY_PATH"]
        if mod_lib_path.endswith(".so"):
            neuron.h.nrn_load_dll(mod_lib_path)
        else:
            neuron.load_mechanisms(mod_lib_path)
        res = mod_lib_path
    elif os.path.isdir('x86_64'):
        # NEURON 8.* automatically load these mechamisms
        res = os.path.abspath('x86_64')
    else:
        res = "No mechanisms are loaded."

    return res


def _register_legacy_morphio_wrapper_alias() -> None:
    """Expose the H5 morphology reader as a top-level ``morphio_wrapper``.

    Emodel hoc templates generated by older BluePyOpt / neurodamus pipelines
    load the reader with a bare import::

        nrnpython("from morphio_wrapper import MorphIOWrapper")

    bluecellulab ships it as ``bluecellulab.cell.morphio_wrapper`` (and its own
    ``MorphIO.hoc`` uses that dotted path), so with such a template the bare
    import fails, the hoc prints
    ".h5 morphlogy used but cannot load 'morphio_wrapper'." and calls
    ``quit()``, which terminates the whole process.

    Registering the alias keeps those templates working without having to edit
    circuit data. ``setdefault`` is used so a real top-level ``morphio_wrapper``
    module (e.g. provided by another package) always takes precedence.
    """
    import sys

    from bluecellulab.cell import morphio_wrapper

    sys.modules.setdefault("morphio_wrapper", morphio_wrapper)


def import_hoc(neuron: ModuleType) -> None:
    """Import hoc dependencies."""
    _register_legacy_morphio_wrapper_alias()
    neuron.h.load_file("stdrun.hoc")  # nrn
    hoc_files = [
        "Cell.hoc",  # ND
        "TDistFunc.hoc",  # ND, test dependency
        "TStim.hoc",  # ND
        "MorphIO.hoc",  # H5 morphology support (loaded after Cell.hoc)
    ]

    for hoc_file in hoc_files:
        hoc_file_path = str(resources.files("bluecellulab") / f"hoc/{hoc_file}")
        with CaptureOutput() as stdoud:
            neuron.h.load_file(hoc_file_path)
            logger.debug(f"Loaded {hoc_file}. stdout from the hoc: {stdoud}")


def print_header(neuron: ModuleType, mod_lib_path: str) -> None:
    """Print bluecellulab header to stdout."""
    logger.debug(f"Imported NEURON from: {neuron.__file__}")
    logger.debug(f"Mod lib: {mod_lib_path}")


@run_once
def _load_mod_files() -> None:
    """Import hoc and mod files."""
    logger.debug("Loading the mod files.")
    mod_lib_paths = import_mod_lib(neuron)
    print_header(neuron, mod_lib_paths)


def load_mod_files(func):
    def wrapper(*args, **kwargs):
        _load_mod_files()
        return func(*args, **kwargs)
    return wrapper
